### ISSUE TITLE
Add other shells and programs.

### ISSUE THREAD

**Issue by DmitryHetman** [n3rdopolis/rebeccablackos#1]
Shells:
Velox
Orbital
Maynard
Motorcar
Way Cooler	
Maze Compositor
Grefsen
Programs:
st-wayland
mpv
epiphany
midori

**Comment by n3rdopolis** [comment]
I already have Orbital, although not on the latest prerelease ISOs because it needs to be updated for Weston 2.0

I tried Maynard years ago, but it needs an older Weston, even today

Motorcar does not compile with the newest QtWayland

Maze Compositor has not been updated since 2012 it seems, and is Dependant on an old qtwayland

Grephesn seems pretty cool, but it seems to be kind of early, and it requires files to be within the $HOME directory, instead of system wide, so I'll keep an eye on that

I already have mpv

Epiphany and Midori are both web browsers, I already have 3, otter-browser, rekonq, and konqueror.

I tried with velox, It doesn't start with logind, like every other session (or seem to even start nested within an xwayland window). I have wlc, orbment, and sway already for tiling wayland sessions

I could  try st-wayland though
